# Metada file
name: Adds a random joke
description: Shows a random joke on the PR
inputs:
  GITHUB_TOKEN:
    description: The GitHub token used to modify the repository.
runs:
  using: "node12"
  main: "dist/app.js"